### ISSUE TITLE
`and` doesn't seem to have the correct coloring

### ISSUE THREAD

**Issue by phated** [grain-lang/grain-language-server#13]
I'm looking at this example on https://grain-lang.org/docs/constructs/bindings

```
let rec isEven = (n) => {
  if (n > 1) {
    isOdd(n-1)
  } else {
    n == 0
  }
}
and isOdd = (n) => {
  if (n > 1) {
    isEven(n-1)
  } else {
    n == 1
  }
}
```

And the `and` is white, instead of the blue of `let` and `rec`.

I'm not sure if this is just a bug on the website or in here.

**Comment by ospencer** [comment]
The site uses the highlighter from here!
