### ISSUE TITLE
Publish vscode extension to open-vsx.org

### ISSUE THREAD

**Issue by tanfonto** [grain-lang/grain-language-server#25]
Microsoft marketplace does only allow running their extensions from within VS Code (legally that is). There are other Code-based (i.e. Eclipse Theia, VSCodium) or simply vsx compatible (Onivim) editors out there that could profit from it. There's actually growing amount of users that refuse to use the MS-branded builds because of their aggressive telemetry and use the aforementioned VSCodium instead.

**Comment by ng-marcus** [comment]
The intention is to break the LSP away from the pure VSCode extension it currently is - the convenience of the VSCode TS libraries is why it's coded this way at the moment.

I use code-server on my ChromeOS devices, and not having the extension available is hurting me too :).   I'll take a look at publishing to open-vsx.

**Comment by phated** [comment]
(For future me) https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by ng-marcus** [comment]
This looks quite straightforward.  I guess @phated  or @ospencer  should hold the publishing token, but let me know if you need a hand with it.

**Comment by ospencer** [comment]
We can store the token as a secret on GitHub, so no big issue there!

**Comment by ng-marcus** [comment]
I need this emoji: 🤯    I really do learn something new every day!

**Comment by ospencer** [comment]
I published the extension and you can find it here: https://open-vsx.org/extension/grain-lang/vscode-grain

I'm working on getting the namespace warning removed, and you can track that here: https://github.com/EclipseFdn/open-vsx.org/issues/273

I also added the token to publish as a secret in this repository as OVSX_PAT. 👍

**Comment by ospencer** [comment]
I'll go ahead and close this issue since it's published, and I'll update our CI issue to include automatically publishing to Open VSX!

**Comment by ng-marcus** [comment]
I'll go get my Pixelbook and test, thanks!
