### ISSUE TITLE
Doesn't handle CRLF line feeds

### ISSUE THREAD

**Issue by phated** [grain-lang/grain-language-server#46]
When debugging on Windows, I found that my LSP information was incorrect. This seems to happen when the file is using CRLF line feeds instead of LF. I switched to LF and everything started to work.

In #45, I added an `if` statement to add an error on line 1 if your code has CRLF, but I think we should just fix the compiler to support them.

**Comment by marcusroberts** [comment]
I'm looking at this, but can't reproduce it at the moment.  

Was the line number count out, or were the lenses or errors wrong?

**Comment by phated** [comment]
None of the lenses or errors were reported in the right place

**Comment by marcusroberts** [comment]
Are you able to send any files that fail?  My own test ones look fine, as does stdlib.

**Comment by phated** [comment]
All of those will be LF, right? Also, the plugin now defaults all files to LF so you have to do a manual change

**Comment by marcusroberts** [comment]
Good point on stdlib!  I've got three files created in CRLF mode and with the block on CRLF removed it works just fine.

Oh, was this with compiled from source,  or packaged binaries?

**Comment by marcusroberts** [comment]
Reproduced it with the packaged binary!

**Comment by ospencer** [comment]
I think this is actually a bug in the Grain compiler; can have a fix in a bit

**Comment by marcusroberts** [comment]
Yes, it's the LSP mode of the compiler returning the loc incorrectly.     Let me know and I can test on Windows once you have the fix.
