### ISSUE TITLE
Syntax Highlighting issue with division symbols

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain-language-server#64]
![image](https://user-images.githubusercontent.com/40705786/118162805-2d177600-b3ef-11eb-86aa-db91236861bd.png)
Syntax Highlighting issue when it comes to division symbols as can be seen here

**Comment by ospencer** [comment]
Hey @spotandjake, that is the intended behavior. Dividing a whole number by another whole number is a rational literal (fraction) in Grain. You can see the differences here:

![image](https://user-images.githubusercontent.com/7244034/118170192-cea2c580-b3f7-11eb-91f6-6a96c75026a4.png)

`3 / 36` becomes the literal `1/12`, so it highlights differently. The other operations are actual division operations, so they have different highlighting.

**Comment by ospencer** [comment]
This document isn't live yet, but you can see more about it here: https://grain-lang.org/docs/constructs/numbers

**Comment by spotandjake** [comment]
ah okay tthen just looks a little offf i guess thks
